### ISSUE TITLE
Keyboard not set on the number keys by default

### ISSUE THREAD

**Issue by bitcoinvsalts** [lotosbin/react-native-pin-input#1]
on iOs, the keyboard shows up with alpha keys and not the number keys.

**Comment by lotosbin** [comment]
Thanks,
I add a property pinItemProps which  support keyboardType

```jsx harmony
        <PinInput
              pinLength={6}
              pinItemStyle={{width: 50, height: 50}}
              pinItemProps={{keyboardType:'number-pad'}}
              onPinCompleted={(pin) => {
                  this.setState({pin: pin})
              }}
          />
```

ref: https://github.com/lotosbin/react-native-pin-input-sample

**Comment by kenshinman** [comment]
Hi @lotosbin , has this issue been solved? My keyboard input still shows normal keyboard with letters

**Comment by lotosbin** [comment]
@kenshinman This issue was solved in 1.1.1.
need more info; such platform ios/android,react/react-native version ,react-native-pin-input version ...

**Comment by felipecocco** [comment]
I'm still experiencing this issue -- pinItemProps is included as above but regular alphanumeric keyboard shows up. Using latest Expo build, latest react-native-pin-input release, in latest iOS

**Comment by lotosbin** [comment]
![image](https://user-images.githubusercontent.com/221294/35424323-d37052f4-028d-11e8-9cda-8681e7cccd78.png)

**Comment by lotosbin** [comment]
I have tested this issue.and it works on ios.
Could you show me your code?

**Comment by lotosbin** [comment]
@felipecocco

**Comment by felipecocco** [comment]
I made a HUGE mistake -- was testing out on iPad, which obviously doesn't have this numeric keypad; works flawlessly. Sorry for the trouble (and thanks for the tool, been a great asset to my project)
